// GENERATED by scripts/build-finale-sequence.py — do not edit by hand.
// The closing beat: the burger settles into a Dinamo box and the lid shuts.

export const FINALE_DESKTOP_COUNT = 52;
export const FINALE_MOBILE_COUNT = 32;

/**
 * The studio backdrop these frames were shot on. The page fades its own
 * background to this before the beat starts, which is what lets the frames be
 * drawn opaque without showing an edge.
 */
export const FINALE_BACKDROP = "rgb(23, 39, 71)";

/**
 * Where the burger sits inside frame 0, as fractions of the frame. The page
 * scales and offsets this sequence so that box lands exactly on the burger the
 * previous beat ended on, making the handoff invisible.
 */
export const FINALE_ANCHOR = {
  left: 0.1287,
  top: 0.3104,
  right: 0.8593,
  bottom: 0.6745,
};
