#!/usr/bin/env python3
"""
Turn the ice cream turntable frames into the scroll sequence the site scrubs.

    python3 scripts/build-icecream.py

Reads  assets/source/ice-cream1.zip   (30 PNGs, 1920x1080, not served)
Writes public/icecream/{desktop,mobile}/f##.avif  (+ .webp fallbacks)
       public/icecream/still-front.{avif,webp}
       public/icecream/still-back.{avif,webp}
       src/iceFrames.ts

Same matting technique as build-frames.py (see matte.py): the backdrop is
static, reconstructed from a low-order surface fit outside the box the cone
never leaves, then subtracted for a real alpha channel and contact shadow.

Unlike the burger this is a plain 360-degree turntable — the cone doesn't come
apart, so there is no layer geometry to measure. The scroll simply scrubs
straight through the 30 frames.

Requires ffmpeg, avifenc (libavif) and numpy.
"""

import json
import os
import shutil
import sys
import zipfile

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from matte import avif, build_plate, key, load  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets/source/ice-cream1.zip")
OUT = os.path.join(ROOT, "public/icecream")

N_SRC = 30
SRC_W, SRC_H = 1920, 1080

# --- output shape -------------------------------------------------------
DESKTOP_W, DESKTOP_Q = 420, 50
MOBILE_W, MOBILE_Q = 280, 46
# Same reasoning as the burger sequence: the canvas cross-dissolves between
# neighbours, so a coarser mobile set still reads as a continuous spin.
MOBILE_N = 20

# --- the box the cone and its shadow never leave -------------------------
# Measured across all 30 frames: the cone's own bounds are y 288..767,
# x 800..1090, with the shadow falling off just past that. Padded generously
# since the fit only needs pixels *outside* this box to be reliably background.
SUBJECT = (240, 850, 720, 1160)


def main():
    if not os.path.exists(SRC):
        sys.exit(f"missing {SRC}")
    if not shutil.which("avifenc"):
        sys.exit("avifenc not found — install libavif")

    zf = zipfile.ZipFile(SRC)
    print(f"source {SRC_W}x{SRC_H}, {N_SRC} frames")

    print("reconstructing the backdrop…")
    frames = [load(zf, i, SRC_W, SRC_H) for i in range(1, N_SRC + 1)]
    plate = build_plate(frames, SRC_W, SRC_H, SUBJECT)

    print(f"keying {N_SRC} frames…")
    keyed = [key(f, plate) for f in frames]
    del frames

    # crop to the union of every frame, so the cone never shifts in its box
    x0, y0, x1, y1 = SRC_W, SRC_H, 0, 0
    for _, a in keyed:
        m = a > 0.12
        cx, cy = np.nonzero(m.any(0))[0], np.nonzero(m.any(1))[0]
        x0, x1 = min(x0, cx.min()), max(x1, cx.max())
        y0, y1 = min(y0, cy.min()), max(y1, cy.max())
    x0, y0 = int(max(0, x0 - 10)), int(max(0, y0 - 10))
    x1, y1 = int(min(SRC_W - 1, x1 + 10)), int(min(SRC_H - 1, y1 + 10))
    cw, ch = x1 - x0 + 1, y1 - y0 + 1
    print(f"  crop {cw}x{ch} (aspect {cw / ch:.4f}), "
          f"{cw * ch / (SRC_W * SRC_H) * 100:.1f}% of the source area")

    # --- encode -----------------------------------------------------------
    def emit(name, width, q, idxs):
        d = os.path.join(OUT, name)
        shutil.rmtree(d, ignore_errors=True)
        os.makedirs(d)
        height = round(width * ch / cw / 2) * 2
        size = 0
        for n, i in enumerate(idxs):
            rgb, a = keyed[i]
            buf = np.dstack([rgb[y0:y1 + 1, x0:x1 + 1],
                             (a[y0:y1 + 1, x0:x1 + 1] * 255).astype(np.uint8)]).tobytes()
            p = os.path.join(d, f"f{n:02d}.avif")
            avif(buf, cw, ch, width, height, q, p)
            size += os.path.getsize(p)
        print(f"  {name}: {len(idxs)} frames @ {width}x{height} -> {size / 1024:.0f} KB avif")
        return height

    os.makedirs(OUT, exist_ok=True)
    desktop = list(range(len(keyed)))
    mobile = [round(i * (len(keyed) - 1) / (MOBILE_N - 1)) for i in range(MOBILE_N)]
    dh = emit("desktop", DESKTOP_W, DESKTOP_Q, desktop)
    emit("mobile", MOBILE_W, MOBILE_Q, mobile)

    # stills for reduced motion — front-on and the opposite side, so the pair
    # still reads as "it turns" even without the scrub. Generated, not hand-made.
    half = len(keyed) // 2
    for name, i in (("still-front", 0), ("still-back", half)):
        rgb, a = keyed[i]
        buf = np.dstack([rgb[y0:y1 + 1, x0:x1 + 1],
                         (a[y0:y1 + 1, x0:x1 + 1] * 255).astype(np.uint8)]).tobytes()
        avif(buf, cw, ch, DESKTOP_W, dh, 58, os.path.join(OUT, f"{name}.avif"), webp=True)
    print("  stills: still-front, still-back")

    with open(os.path.join(ROOT, "src/iceFrames.ts"), "w") as fh:
        fh.write(f"""// GENERATED by scripts/build-icecream.py — do not edit by hand.
// Geometry of the ice cream turntable sequence in public/icecream/.

/** width / height of every frame */
export const ASPECT = {cw / ch:.5f};

export const DESKTOP_COUNT = {len(desktop)};
export const MOBILE_COUNT = {len(mobile)};

/** mobile frame i is a copy of desktop frame MOBILE_MAP[i] */
export const MOBILE_MAP: readonly number[] = {json.dumps(mobile)};
""")
    print("wrote src/iceFrames.ts")


if __name__ == "__main__":
    main()
