// GENERATED by scripts/build-icecream.py — do not edit by hand.
// Geometry of the ice cream turntable sequence in public/icecream/.

/** width / height of every frame */
export const ASPECT = 0.53451;

export const DESKTOP_COUNT = 30;
export const MOBILE_COUNT = 20;

/** mobile frame i is a copy of desktop frame MOBILE_MAP[i] */
export const MOBILE_MAP: readonly number[] = [0, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 24, 26, 27, 29];
